### ISSUE TITLE
Add Lazy Single Fields

### ISSUE THREAD

**Issue by boomsb** [charlieridley/emu#37]
Would it be possible to make single properties lazy loadable? I'd propose a syntax similar to below.

``` java
App.Company = Emu.Model.extend({
    //...
    account: Emu.field("App.Account", {lazy: true})
});

App.Account = Emu.Model.extend({});

//Get a lazy property
var account = company.get("account");
//GET request to:   http://www.mysite.com/companies/1/account
//Response: [{id:"123456"}]
```

**Comment by charlieridley** [comment]
This change needs both singular and plural names in the url (companies and account).

In order to get this to work I had to provide a way to allow you to define a singular and pluralized resource name for a model if you are using an override. I added a flag to the override function so you can do it like this:

``` javascript
App.Person = Emu.Model.extend({
  resourceName: function(isSingular){
    return isSingular ? "person" : "people";
  }
})
```

If you choose to specify an overriden resource name like this:

``` javascript
App.Person = Emu.Model.extend({
  resourceName: "people"
})
```

then it will always use the same name for singular and plural.

If you specify no override it will default to normal behaviour (people and peoples).

Anyway, this should work now

**Comment by charlieridley** [comment]
I just realised this isn't completely working. When saving it doesn't send the request to correct URL

**Comment by boomsb** [comment]
Haven't tried any saves, but loads are working great, thanks again.

One comment, I was expecting it to load based on the property name. Here's what I was expecting:

``` javascript
App.Foo = Emu.Model.extend();

App.Bar = Emu.Model.extend({
  bit : Emu.field('App.Foo', {lazy : true}),
  baz : Emu.field('App.Foo', {lazy : true})
});

bar.get('bit');
//GET request to:   http://www.mysite.com/bar/1/bit
//Response: {...}

bar.get('baz');
//GET request to:   http://www.mysite.com/bar/1/baz
//Response: {...}
```

Not a show stopper since I can easily extend Foo into another class or two to get different routes.

**Comment by charlieridley** [comment]
Yeah I agree. That means changing the way the lazy collections work as well which is a breaking change so I'll have to do that as a seperate item

**Comment by charlieridley** [comment]
Created issue for this https://github.com/charlieridley/emu/issues/39

**Comment by charlieridley** [comment]
Ok fixed this now
